Add Hunger System, Basic Food Item Use.
KryptonMC/Krypton pull request #59
Opened 2021-11-12 03:50 UTC by tomlister

I successfully resigned this. Soft reset is much easier.

Please refactor, contains some hardcoded values. TimedHandler needs a way of finishing a use interaction once a minimum time threshold has been reached.
Possible solution is to set active handler on player object, then tick until time delta min has been exceeded and then force finishUse. I implemented this but then reverted my changes as I think it's up to @BomBardyGamer to decide how this should be done. I also added some methods to the inventory to be able to set the item of a hand.

2021-11-12 10:20 UTC, tomlister commented
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

:(

Will fix.

2021-11-12 10:25 UTC, BomBardyGamer commented
I get that too, so I'm betting no

2021-11-12 17:41 UTC, BomBardyGamer requested changes
Overall, looks good to me. Just a few nitpicks and queries here that I want addressed.

2021-11-12 17:41 UTC, BomBardyGamer commented on server/src/main/kotlin/org/kryptonmc/krypton/entity/player/KryptonPlayer.kt
> +            field = value
I'm pretty sure that this ends up being a field anyway, so there's no need to call super or reference super in any way in this case. Though, I recommend that you remove the backing field from this override and have it call super, to avoid us generating a backing field for this override.

This would look something like this:
```kotlin
override var health: Float
    get() = super.health
    set(value) {
        super.health = value
        session.send(PacketOutUpdateHealth(health, foodLevel, foodSaturationLevel))
    }
```

2021-11-12 17:41 UTC, BomBardyGamer commented on server/src/main/kotlin/org/kryptonmc/krypton/entity/player/KryptonPlayer.kt
> +    private fun hungerMechanic() {
This could probably do with either more comments or more of these magic values extracted in to constants. The first questions I have when looking through this code are things like "where does this 4f come from?" and "why is 4 seconds how long we tick for?". These aren't questions I want you to answer directly to me, I want you to explain why you are using those exact numbers in the code.

2021-11-12 17:41 UTC, BomBardyGamer commented on server/src/main/kotlin/org/kryptonmc/krypton/entity/player/KryptonPlayer.kt
> +            if (value > 0) foodExhaustionLevel += 0.01F * value.toFloat()
Again, this and the one below are magic values.

2021-11-12 17:41 UTC, BomBardyGamer commented on server/src/main/kotlin/org/kryptonmc/krypton/entity/player/KryptonPlayer.kt
> +    override var foodLevel: Int = 20
![Magic](https://c.tenor.com/wn2_Qq6flogAAAAC/magical-magic.gif)

2021-11-12 17:41 UTC, BomBardyGamer commented on server/src/main/kotlin/org/kryptonmc/krypton/entity/player/KryptonPlayer.kt
> +    override var foodSaturationLevel: Float = 5f
![Magic](https://c.tenor.com/wn2_Qq6flogAAAAC/magical-magic.gif)

2021-11-12 17:41 UTC, BomBardyGamer commented on server/src/main/kotlin/org/kryptonmc/krypton/item/handler/FoodHandler.kt
> +        player.foodLevel += 8
This and below are magic values

2021-11-12 17:41 UTC, BomBardyGamer commented on server/src/main/kotlin/org/kryptonmc/krypton/network/handlers/PlayHandler.kt
> +                (server.itemManager.handler(player.inventory[player.inventory.heldSlot].type) as KryptonItemTimedHandler).finishUse(player, player.hand)
We should probably check this here first, especially considering people can override the default handlers for types with their own handlers (which will be addressed later).

```suggestion
val handler = server.itemManager.handler(player.inventory[player.inventory.heldSlot].type)
if (handler !is KryptonItemTimedHandler) return
handler.finishUse(player, player.hand)
```

2021-11-12 17:41 UTC, BomBardyGamer commented on server/src/main/kotlin/org/kryptonmc/krypton/packet/in/play/PacketInPlayerUseItem.kt
> +    val hand = buf.readEnum<Hand>()
```suggestion

    val hand = buf.readEnum<Hand>()
```

2021-11-12 17:41 UTC, BomBardyGamer commented on server/src/main/kotlin/org/kryptonmc/krypton/world/block/handler/KryptonBlockHandler.kt
> +        player.foodExhaustionLevel += 0.005f
![Magic](https://c.tenor.com/wn2_Qq6flogAAAAC/magical-magic.gif)

2021-11-13 03:50 UTC, tomlister commented on server/src/main/kotlin/org/kryptonmc/krypton/item/handler/FoodHandler.kt
> +        player.foodLevel += 8
This is just for testing.

2021-11-13 13:26 UTC, tomlister commented
Feel free to push whenever

2021-11-13 13:27 UTC, tomlister commented
Merge*

2021-11-13 23:36 UTC, BomBardyGamer commented on server/src/main/kotlin/org/kryptonmc/krypton/entity/player/KryptonPlayer.kt
> +import kotlin.math.*
IntelliJ can you please not violate my style guides? kthxbye

2021-11-14 01:21 UTC, merged