Feature/passengers - Mounting & Dismounting
KryptonMC/Krypton pull request #62
Opened 2021-11-14 09:45 UTC by tomlister

- Added PacketInPlayerInteractEntity
- Added PacketInSteerVehicle
- Added PacketOutSetPassengers
- Added addPassenger and removePassenger method to Entity
- Added vehicle attribute to Entity
- Added handlers to mount and dismount players.

TODO:
- Handle steering and jumping in PacketInSteerVehicle handler.
- What happens if an entity vehicle is removed, how, or should we, clear the passenger's vehicle attribute?

2021-11-14 19:36 UTC, BomBardyGamer requested changes
Overall, another great PR. Just a few nitpicks and one big issue, all of which are easily solvable.

2021-11-14 19:36 UTC, BomBardyGamer commented on server/src/main/kotlin/org/kryptonmc/krypton/entity/KryptonEntity.kt
> +    final override val passengers: MutableList<Entity> = ArrayList()
As was mentioned by Brister Mitten on Discord, this should probably be a set, to guarantee that we don't get duplicates.

Also, `mutableListOf` returns an `ArrayList` anyway, and I also think it's best to use that, just in case the Kotlin team decide to change their mind and think a different list implementation would be better to use.

2021-11-14 19:36 UTC, BomBardyGamer commented on server/src/main/kotlin/org/kryptonmc/krypton/network/handlers/PlayHandler.kt
> +        if (flagInt and 0x01 == 0x01) /* noop */
I'd rather you not leave in if statements that do nothing like this, as they are prone to bugs and unintended behaviour. If you want to leave something in for future use, just comment it out. Though this should be removed entirely, since there's no need to handle and check for behaviour that we don't support.

2021-11-14 19:36 UTC, BomBardyGamer commented on server/src/main/kotlin/org/kryptonmc/krypton/packet/out/play/PacketOutSetPassengers.kt
>          buf.writeIntArray(passengers.map { (it as KryptonEntity).id }.toIntArray())
All I can say to this is:
![No](https://c.tenor.com/F4vgEqTjG7AAAAAd/tracey-morgan-no.gif)

You realise this is going to do the following:
- Create a new list of integers
- Create a new integer array

I can recommend the following suitable replacement:
```suggestion
        buf.writeVarInt(passengers.size)
        passengers.forEach { buf.writeVarInt((it as KryptonEntity).id) }
```

2021-11-14 19:46 UTC, tomlister commented on server/src/main/kotlin/org/kryptonmc/krypton/packet/out/play/PacketOutSetPassengers.kt
>          buf.writeIntArray(passengers.map { (it as KryptonEntity).id }.toIntArray())
Ah yes. That seems like a much more efficient method

2021-11-15 03:26 UTC, tomlister commented on server/src/main/kotlin/org/kryptonmc/krypton/entity/KryptonEntity.kt
> +    final override val passengers: MutableList<Entity> = ArrayList()
Facts

2021-11-15 03:26 UTC, tomlister commented on server/src/main/kotlin/org/kryptonmc/krypton/network/handlers/PlayHandler.kt
> +        if (flagInt and 0x01 == 0x01) /* noop */
Yeah, fair enough.

2021-11-15 23:26 UTC, tomlister commented
Still need to handle unloading. Will do this today.

2021-11-20 15:58 UTC, BomBardyGamer approved these changes

2021-11-20 15:58 UTC, merged